---
- hosts: master
  become: yes
  tasks: 
    - name: Install Apache
      package:
        name: apache2
        state: latest
    - name: Start theApache service
      service:
         name: apache2
         state: started 
    - name: Install Php
      package:
        name: php
      state: present
